defmodule ExAws.Bedrock.EventStream do
  @moduledoc """
  Handle streaming of output generated by models.

  The model detail returned by `ExAws.Bedrock.get_foundation_model/1` must have:

      responseStreamingSupported: true

  This requires `hackney` otherwise will fail at runtime.
  """

  defdelegate build_request_url(post_operation, config), to: ExAws.Request.Url, as: :build

  if Kernel.function_exported?(:hackney, :post, 4) do
    @http_ua :hackney_request.default_ua()
    @library_version Application.spec(:ex_aws_bedrock)[:vsn]
    @user_agent "#{@http_ua} ex_aws/bedrock/#{@library_version}"
  else
    def stream_objects!(_, _, _) do
      raise "Bedrock response streaming requires hackney in your mix dependencies"
    end
  end
end
