name: ci
on: [push, pull_request]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: [23.x, 24.x, 25.x, 26.x]
        elixir: [1.14.x, 1.15.x, 1.16.x]
        exclude:
          - otp: 23.x
            elixir: 1.16.x
          - otp: 23.x
            elixir: 1.15.x
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
        if: matrix.elixir == '1.15.x'
      - run: mix credo --strict
        if: matrix.elixir == '1.15.x'
      - run: mix dialyzer
        if: matrix.elixir == '1.15.x' && matrix.otp == '25.x'
      - run: mix test